### ISSUE TITLE
Design Changes.

### ISSUE THREAD

**Issue by Monsterous915** [stevemk14ebr/Snake#2]
Hi, this is not an issue but I have made some design changes to the application and if you are interested I can do a pull request.

![SnakeHome](https://user-images.githubusercontent.com/33160251/63960481-ce0fa300-ca4b-11e9-9d6d-4e7563ea8f30.PNG)
![SnakeTutorial](https://user-images.githubusercontent.com/33160251/63960487-d667de00-ca4b-11e9-823d-9a6cf50ed6e0.PNG)
![SnakeGame](https://user-images.githubusercontent.com/33160251/63960488-d8ca3800-ca4b-11e9-9d10-17e4764b535c.PNG)
![SnakeGameOver](https://user-images.githubusercontent.com/33160251/63960492-db2c9200-ca4b-11e9-8eef-41596c2db14f.PNG)

**Comment by stevemk14ebr** [comment]
I love it, please PR

**Comment by stevemk14ebr** [comment]
have your PR change the screenshot in the readme too please

**Comment by Monsterous915** [comment]
I am not sure if I modified the README.md file correctly but I did submit a pull request.

Sent from Mail for Windows 10
